force-app/main/default/objects/Configuration_Log_Configuration__mdt/Configuration_Log_Configuration__mdt.object-meta.xml
<CustomObject>
    <description>This custom metadata type is for all the configuration for the Configuration Log functionality.</description>
    <label>Configuration Log Configuration</label>
    <pluralLabel>Configuration Log Configurations</pluralLabel>
</CustomObject>

force-app/main/default/objects/Configuration_Log_Configuration__mdt/fields/Salesforce_Version__c.field-meta.xml
<CustomField>
    <fullName>Salesforce_Version__c</fullName>
    <description>This is the Salesforce version of the Metadata API to use.</description>
    <label>Salesforce Version</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/ConfigurationLogHelper.cls
public class ConfigurationLogHelper {
    
    public static Attachment getPackageXmlFile(List<ConfigurationLogCmpController.FilePropertyWrapper> configLog) {
        if(configLog == null || configLog.size() == 0)
            return null;
        
        Map<String, Set<String>> components = new Map<String, Set<String>>();
        
        for(ConfigurationLogCmpController.FilePropertyWrapper log : configLog) {
            if(components.get(log.componentType) == null) 
                components.put(log.componentType, new Set<String>());
            
            components.get(log.componentType).add(log.fullName);
        }
        
        Attachment attch = new Attachment(); 
        String packageXml = ConfigurationLogHelper.getPackageXmlString(components);
        String filename = 'Package - (';
        List<String> componentList = new List<String>(components.keySet()); 
        
        for(Integer i = 0; i < componentList.size(); i++) {
            filename += componentList.get(i);
            
            if((i + 1) != componentList.size())
                filename += ', ';
        }
        
        Blob file = Blob.valueOf(packageXml);
        attch.Body = file;
        attch.Name = filename + ') -' + DateTime.now() + '.xml';
        attch.IsPrivate = false;
        
        return attch;  
    }
    
    public static String getPackageXmlString(Map<String, Set<String>> components) {
        if(components == null || components.keySet().size() == 0)
            return '';
        
        String packageXml = '<?xml version="1.0" encoding="UTF-8"?>\n<Package xmlns="http://soap.sforce.com/2006/04/metadata">\n';
        
        for(String name : components.keySet()) {
            String memberList = '';
            
            for(String members : components.get(name)) {
                List<Object> stringFormatMember = new List<Object> { members };
                    memberList += String.format('\t\t<members>{0}</members>\n', stringFormatMember);
            }
            
            List<Object> componentTypeList = new List<Object> { memberList, name };
                packageXml += String.format('\t<types>\n{0}\t\t<name>{1}</name>\n\t</types>\n', componentTypeList);
        }
        
        // Perform a query to get the Salesforce verision being used to access the Metadata API
        List<Configuration_Log_Configuration__mdt> logsMDT = [SELECT Salesforce_Version__c FROM Configuration_Log_Configuration__mdt where DeveloperName='Component_List'];
        Decimal salesforceVersion = [SELECT ApiVersion FROM ApexClass WHERE Name = 'ConfigurationLogHelper' LIMIT 1].ApiVersion;
        
        if(logsMDT.size() > 0)
            salesforceVersion = logsMDT.get(0).Salesforce_Version__c;
        
        packageXml += '\t<version>' +  String.valueOf(salesforceVersion.doubleValue()) + '</version>\n</Package>';
        
        return packageXml;
    }
    
}